name: Rspec and Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [2.7, '3.0', '3.1']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Test with Rspec
      run: |
          bundle exec rspec --format documentation --require spec_helper
  release:
    needs: rspec
    runs-on: ubuntu-latest
    env:
      BUNDLE_DEPLOYMENT: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: |
        gem build
    - name: Zip
      run : |
        zip -r datadog_backup.zip ./*
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        semantic_version: 17
        extra_plugins: |
          @semantic-release/changelog@5
          @semantic-release/git@9
    - name: push to rubygems
      if: ${{ steps.semantic.output.new_release_published }}
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_TOKEN }}
        RUBYGEMS_MFA_KEY: ${{ secrets.RUBYGEMS_MFA_KEY }}
        GEM_VERSION: ${{ steps.semantic.output.new_release_version }}
      run: |
        sudo apt-get install -y oathtool jq
        TOKEN=$(oathtool --base32 --totp ${RUBYGEMS_MFA_KEY:?})
        gem push datadog_backup-${GEM_VERSION:?}.gem  --otp ${TOKEN:?}