name: Validate PR Title
on: 
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
    - name: Validate PR Title
      uses: amannn/action-semantic-pull-request@v5.5.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        validateSingleCommit: true